
def sum_even_Fibonacci_numbers(max):
    ''' Problem 002: Even Fibonacci numbers
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed
    four million, find the sum of the even-valued terms.
    Sol: 4613732 '''
    sum = 0
    prev = 0
    curr = 1
    fib = prev + curr
    while fib <= max:
        if fib %2 == 0:
            sum += fib
        prev = curr
        curr = fib
        fib = prev + curr
    return sum

def main():
    print(sum_even_Fibonacci_numbers(4000000))

if __name__ == '__main__':
    main()
